version: "3.7"

services:
  mongo:
    image: mongo
    container_name: surt_database
    environment:
      - MONGO_INITDB_DATABASE=surt
      - MONGO_INITDB_ROOT_USERNAME=surt
      - MONGO_INITDB_ROOT_PASSWORD=surt
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surt_frontend
    environment:
      - BASE_ADDRESS=http://localhost:4000
      - MONGODB_URI=mongodb://surt:surt@mongo:27017/
      - MONGODB_DB=surt
    ports:
      - 4000:3000
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  database: {}