apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  labels:
    app: surt
    env: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi